
"""This function is incomplete
    manuscriptProximityScore() will return a Vector of PageScore DataTypes. This will provide
    page-by-page data on how well a manuscript aligns with the traditional proximity hypothesis
    $(SIGNATURES)
"""
function manuscriptProximityScore(newpages)
    msScore = Vector{PageScore}
    for pg in newpages
        #Function here to check a single page according to the proximity hypothesis
        push(msScore, comparePage(pg))
    end
    
end
"""This function is incomplete
manuscriptChurikScore() will return a Vector of PageScore DataTypes. This will provide page-by-page data 
on how well a manuscript aligns with the Churik zone hypothesis
"""
function manuscriptChurikScore(newpages)
    msScore = Vector{PageScore}
    for pg in newpages
        push(msScore, comparePage(pg))
    end

end

"""This function is incomplete
comparePage() will take one parameter: the positions of text-scholia pairs on a page generated by the optimization function.
It will return a PageScore data type containing the page id, number of successes, and the total number of pairs
"""
function comparePage(newpg)
    score::PageScore
    orig = pairsDimensions()
    xvals = orig[5]
    yvals = orig[6]
    for i in eachindex(orig[5])
        if orig[5][i] == newpg[PLACEHOLDER][i] && orig[6][i] == newpg[PLACEHOLDER][i]
            score.successes += 1
        end
    end
    return score
end